export const BOOKS = [
  {
    id: "book-1",
    title: "Parts of Speech-1",
    url: "/books/parts-of-speech-1.pdf",
    description:
      "Master the essentials of English grammar with this concise workbook for beginners. It provides clear definitions, examples, and practical exercises covering the eight primary parts of speech to help build foundational writing skills.",
    coverImage: "/images/books/parts-of-speech-1.png",
    authorId: "author-1",
    publishDate: "2025-12-22T00:00:00.000Z",
  },
  {
    id: "book-2",
    title: "Jinsar Test",
    url: "/books/jinsar-test.pdf",
    description:
      "A 100-question English grammar assessment to be completed in 100 minutes. It covers core topics such as parts of speech—including nouns, verbs, adjectives—and tests sentence structure and classification skills.",
    coverImage: "/images/books/jinsar-test.png",
    authorId: "author-1",
    publishDate: "2025-12-22T00:00:00.000Z",
  },
  {
    id: "book-3",
    title: "Precis Writing Presentation",
    url: "/books/precis-writing.pptx",
    description:
      "A clear guide to Précis Writing for CSS exams by Jinsar Alee Bhatti, covering key rules, techniques, and examples for mastering concise summarization.",
    coverImage: "/images/books/precis-writing.png",
    authorId: "author-1",
    publishDate: "2025-12-22T00:00:00.000Z",
  },
  {
    id: "book-4",
    title: "Criminology Notes Jinsar",
    url: "/books/criminology-notes-jinsar",
    description:
      "Comprehensive criminology notes covering key concepts, theories, and case studies for CSS examination preparation.",
    coverImage: "/images/books/criminology-book.png",
    authorId: "author-1",
    publishDate: "2025-12-22T00:00:00.000Z",
    // readerType: "image-pages"
    readerType: "pdf",
    pdfUrl: "/books/criminology-notes-jinsar.pdf",
    // Pages array - each page should be an image in /public/images/books/criminology-notes/
    // Format: page-1.jpg, page-2.jpg, etc. (or .png)
    // You'll need to convert the PDF pages to images and place them in /public/images/books/criminology-notes/
    // pages: [
    //   "/images/books/criminology-book.png",
    //   "/books/criminology-notes-jinsar/page-0001.jpg",
    //   "/books/criminology-notes-jinsar/page-0002.jpg",
    //   "/books/criminology-notes-jinsar/page-0003.jpg",
    //   "/books/criminology-notes-jinsar/page-0004.jpg",
    //   "/books/criminology-notes-jinsar/page-0005.jpg",
    //   "/books/criminology-notes-jinsar/page-0006.jpg",
    //   "/books/criminology-notes-jinsar/page-0007.jpg",
    //   "/books/criminology-notes-jinsar/page-0008.jpg",
    //   "/books/criminology-notes-jinsar/page-0009.jpg",
    //   "/books/criminology-notes-jinsar/page-0010.jpg",
    //   "/books/criminology-notes-jinsar/page-0011.jpg",
    //   "/books/criminology-notes-jinsar/page-0012.jpg",
    //   "/books/criminology-notes-jinsar/page-0013.jpg",
    //   "/books/criminology-notes-jinsar/page-0014.jpg",
    //   "/books/criminology-notes-jinsar/page-0015.jpg",
    //   "/books/criminology-notes-jinsar/page-0016.jpg",
    //   "/books/criminology-notes-jinsar/page-0017.jpg",
    //   "/books/criminology-notes-jinsar/page-0018.jpg",
    //   "/books/criminology-notes-jinsar/page-0019.jpg",
    //   "/books/criminology-notes-jinsar/page-0020.jpg",
    //   "/books/criminology-notes-jinsar/page-0021.jpg",
    //   "/books/criminology-notes-jinsar/page-0022.jpg",
    //   "/books/criminology-notes-jinsar/page-0023.jpg",
    //   "/books/criminology-notes-jinsar/page-0024.jpg",
    //   "/books/criminology-notes-jinsar/page-0025.jpg",
    //   "/books/criminology-notes-jinsar/page-0026.jpg",
    //   "/books/criminology-notes-jinsar/page-0027.jpg",
    //   "/books/criminology-notes-jinsar/page-0028.jpg",
    //   "/books/criminology-notes-jinsar/page-0029.jpg",
    //   "/books/criminology-notes-jinsar/page-0030.jpg",
    //   "/books/criminology-notes-jinsar/page-0031.jpg",
    //   "/books/criminology-notes-jinsar/page-0032.jpg",
    //   "/books/criminology-notes-jinsar/page-0033.jpg",
    //   "/books/criminology-notes-jinsar/page-0034.jpg",
    //   "/books/criminology-notes-jinsar/page-0035.jpg",
    //   "/books/criminology-notes-jinsar/page-0036.jpg",
    //   "/books/criminology-notes-jinsar/page-0037.jpg",
    //   "/books/criminology-notes-jinsar/page-0038.jpg",
    //   "/books/criminology-notes-jinsar/page-0039.jpg",
    //   "/books/criminology-notes-jinsar/page-0040.jpg",
    //   "/books/criminology-notes-jinsar/page-0041.jpg",
    //   "/books/criminology-notes-jinsar/page-0042.jpg",
    //   "/books/criminology-notes-jinsar/page-0043.jpg",
    //   "/books/criminology-notes-jinsar/page-0044.jpg",
    //   "/books/criminology-notes-jinsar/page-0045.jpg",
    //   "/books/criminology-notes-jinsar/page-0046.jpg",
    //   "/books/criminology-notes-jinsar/page-0047.jpg",
    //   "/books/criminology-notes-jinsar/page-0048.jpg",
    //   "/books/criminology-notes-jinsar/page-0049.jpg",
    //   "/books/criminology-notes-jinsar/page-0050.jpg",
    //   "/books/criminology-notes-jinsar/page-0051.jpg",
    //   "/books/criminology-notes-jinsar/page-0052.jpg",
    // ],
  },
];
