export const CHAPTERS = [
  {
    chapterId: "chapter-1",
    novelId: "novel-1",
    chapterNumber: 1,
    title: "Back to School Life",
    content: [
      "The atmosphere in Bhurban was serene. Nestled amidst the rolling hills, the venue hosted officers from across the country—and beyond. It was a rare convergence of minds, ideas, and cultures, all gathered under the pretext of learning and collaboration.",
      "Bhurban is a picturesque hill station in the Murree Hills region, located in Punjab, Pakistan, approximately 13 kilometers from the popular tourist destination of Murree. Nestled in the foothills of the Himalayas, Bhurban is renowned for its serene environment, lush green meadows, dense pine forests, and breathtaking views of the mountains.",
      "I remember stepping into Bhurban with excitement bubbling within me, though I wore the mask of composure. The journey from Karachi had been long but exhilarating, a chance to momentarily escape the grind of city life. Little did I know, something unexpected awaited me?",
      "On the first day, everyone lingered around Xavier Hall, an elegant yet intimidating space, waiting for the introductory class. The air buzzed with the dull hum of strangers attempting to bridge the awkward gaps between them. Unable to suppress my restlessness, I slipped out for a smoke.",
      "The crisp mountain air greeted me, but a problem quickly surfaced—I had forgotten my cigarette packet in my room on the second floor. With a sigh, I trudged back up the stairs, my mind wandering over the agenda of the day.",
      "As I stepped out of my room with the packet in hand, the echo of hurried footsteps followed me down the hallway.",
      "“Excuse me?”",
      "Startled, I turned to find the source of the voice.",
      "She stood a few feet away, her presence commanding attention without effort. A girl in a crisp white shirt and black pants, her hair cascading freely over her shoulders, and a smile that could melt glaciers. For a moment, I forgot where I was—or perhaps even who I was.",
      "“Yes?” I managed, my voice barely audible.",
      "“I’m Sanvi. Sanvi Sinha,  basically from India presently settled in United Kingdom,” Her voice was calm yet confident, with a lilting charm that added to the spell she seemed to cast. “What’s your good name?”",
      "Caught off guard by her directness and mesmerized by her beauty, my words stumbled over themselves. “Mmm... Musavir,” I stammered, feeling the heat rise to my face.",
      "She chuckled softly, clearly amused by my discomfort, her eyes dancing with mischief. “Well, Musavir, nice to meet you.”",
      "Without waiting for a response, she turned and walked away, leaving me standing there, clutching my cigarette packet like it was the only thing anchoring me to reality.",
      "For the next few moments, I remained rooted to the spot, replaying the encounter in my head. Who was this Sanvi? And why did her presence feel like a spark that had ignited something within me?",
      "The sound of murmuring voices and shuffling feet from Xavier Hall snapped me back to the present. The class was about to begin, and yet, I couldn't shake off the lingering traces of her smile.",
      "As I re-entered Xavier Hall, my heart raced—not because of the training, but because of the whirlwind that had just occurred in the corridor. My mind was still spinning from my encounter with Sanvi. Thinking I might be late for the first session, I braced myself for the judgmental glances that often follow tardiness. But to my relief, the trainer hadn’t arrived yet.",
      "I quickly scanned the room and found a seat behind Rimsha, a colleague from my office. She was chatting animatedly with a group of officers from other departments, exchanging introductions and expectations for the training. I joined in, trying to focus, but my mind kept straying to the girl in white and black.",
      "The casual conversation was interrupted by the creak of the door swinging open. The soft chatter came to a halt, and I instinctively turned toward the entrance. At first, all I could see were her feet. White, polished, and delicate, adorned with a dainty anklet on her left foot, just above her shoes. The subtle clinking of the chain felt like a melody against the silence, and for a moment, the world around me faded.",
      "The footsteps echoed in my mind as though they were part of a romantic overture. Slowly, I raised my gaze, and there she was—Sanvi. Her presence filled the room, effortlessly commanding attention. My throat went dry, my pulse quickened, and it felt as though my heart was sinking into some uncharted depth.",

      "She walked to the rostrum with the confidence of someone who knew they belonged in the spotlight. Her smile was faint but warm, and her eyes briefly swept over the crowd before landing on me. For a split second, I felt like I was the only one in the room, as if her smile was a secret meant only for me.",
      "She spoke, her voice clear and confident, carrying the hint of a smile.",
      "“I am Sanvi Sinha, your master trainer for this project,” she began, her words resonating in the silent hall. “I’ve traveled here all the way from India, not just to train you, but to experience something new—to meet people, to share, and to learn.”",
      "She paused, letting her words settle, and then added with a playful glint in her eyes, “And I must say, a good experience has already amused me.”",
      "Her gaze met mine again, and this time, her smile deepened, carrying an unmistakable hint of mischief. I could feel the heat rise to my face as I struggled to suppress a smile of my own. Was she talking about me? Or was this just her way of connecting with the group?",
      "The room erupted in applause, but my hands remained frozen in place. My thoughts were trapped in the magnetic pull of her presence. Sanvi had effortlessly taken control of the moment, and with her, she had taken a piece of my attention—perhaps even my heart.",
      "As she began explaining the agenda for the training, I found myself unable to focus. Her words sounded distant, like background music to the symphony playing in my mind. My colleagues asked questions, and discussions ensued, but I remained quiet, lost in my thoughts.",
      "One thing was certain: this training was going to be more than just an academic experience.",
    ],
    publishDate: "2024-03-01T00:00:00.000Z",
  },
];
